// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProviders from "@features/providers/AppProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "AI Chat Mermaid",
//   description: "Generated by Neira",
// };

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: { default: "AI-Chat", template: "%s — AI-Chat" },
  description: "Учебный проект для линейки курсов: AI на Django и Next",
  icons: { icon: [{ url: "/favicon.ico" }] },
  keywords: [
    "AI",
    "ЮKassa",
    "mermaid",
    "SaaS",
    "stepik",
    "Next.js",
    "django",
  ],
  openGraph: {
    title: "AI-Chat",
    description:
      "Учебный проект для линейки курсов: AI на Django и Next",
    url: siteUrl,
    siteName: "AI-Chat",
    images: [
      {
        url: "/images/og.png",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
  alternates: {
    canonical: siteUrl,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppProviders>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
